### ISSUE TITLE
Why wasn't Consul Template used?

### ISSUE THREAD

**Issue by dissipate** [autopilotpattern/elk#3]
Is there a reason you didn't just use Consul Template instead of this bash script https://github.com/tgross/triton-elk/blob/master/logstash/onStart.sh? Looks like you used it in this example: https://www.joyent.com/blog/applications-on-autopilot

**Comment by tgross** [comment]
consul-template would certainly work. But it's a pretty simple find-and-replace change so adding consul-template just for a one-line change that could be done by sed didn't seem worth the added dependency.

**Comment by misterbisson** [comment]
@dissipate Does that answer it? We certainly do use and recommend consul-template in a lot of cases, don't doubt that.

Feel free to re-open or create a new issue with other questions.
